import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowDownRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { jhonaLogo } from "@/components/portfolio-shell";
import { isaacProfile, projects } from "@/lib/portfolio-data";

export const Route = createFileRoute("/")({
  head:()=>({meta:[{title:"Isaac Espinoza | Diseñador Gráfico & Fotógrafo"},{name:"description",content:"Portfolio de Isaac Espinoza, Licenciado en Diseño Gráfico y fotógrafo. Identidad visual, branding, diseño gráfico, fotografía, retoque y producción visual."},{property:"og:title",content:"Isaac Espinoza | Diseñador Gráfico & Fotógrafo"},{property:"og:description",content:"Diseño gráfico, fotografía, identidad visual y producción integral."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/"}]}), component: Home
});

const featured=projects.filter((project)=>project.featured).slice(0,4);
function Home(){return <main><section className="relative min-h-[calc(100svh-4rem)] overflow-hidden bg-foreground text-background"><img src={isaacProfile} alt="Retrato de Isaac Espinoza en Encarnación" className="absolute inset-0 h-full w-full object-cover object-[center_42%] opacity-60 md:left-auto md:w-[48%] md:opacity-100"/><div className="absolute inset-0 bg-hero-wash md:hidden"/><div className="relative z-10 flex min-h-[calc(100svh-4rem)] flex-col justify-between px-5 py-7 md:w-[62%] md:px-10 md:py-10"><div className="flex justify-between font-mono text-[9px] uppercase"><span>Portfolio / 2026</span><span>Encarnación · Paraguay</span></div><div><h1 className="font-display text-[clamp(5rem,18vw,12rem)] uppercase leading-[.76]">Isaac<br/>Espinoza<span className="text-primary">.</span></h1><div className="mt-7 grid max-w-2xl gap-5 border-t border-background/30 pt-5 md:grid-cols-2"><p className="font-display text-2xl uppercase leading-none">Diseñador gráfico<br/>+ fotógrafo<br/>+ creador visual</p><p className="max-w-xs text-sm leading-relaxed text-background/75">Creo identidades, imágenes y piezas visuales que comunican con claridad y sensibilidad.</p></div><div className="mt-7 flex flex-wrap gap-3"><Button asChild variant="editorial"><Link to="/proyectos">Ver proyectos <ArrowDownRight/></Link></Button><Button asChild variant="editorialOutline" className="border-background text-background"><Link to="/cv">Ver CV</Link></Button></div></div></div></section>
<section className="border-b border-border px-5 py-20 md:px-10 md:py-32"><span className="section-number">01 / Perfil</span><p className="mt-7 max-w-5xl font-display text-4xl uppercase leading-[.95] md:text-7xl">Diseño para comunicar. Fotografío para conservar. Creo para convertir ideas en experiencias visuales.</p></section>
<section className="px-5 py-20 md:px-10 md:py-28"><div className="mb-12 grid gap-4 md:grid-cols-[1fr_auto] md:items-end"><div><span className="section-number">02 / Selected work</span><h2 className="mt-3 font-display text-6xl uppercase leading-none md:text-8xl">Proyectos<br/>destacados</h2></div><Link to="/proyectos" className="font-mono text-xs uppercase">Ver todos →</Link></div><div className="grid gap-x-6 gap-y-14 md:grid-cols-12">{featured.map((project,index)=><Link key={project.slug} to="/proyectos/$slug" params={{slug:project.slug}} className={`project-tile group ${index===0?'md:col-span-8':index===1?'md:col-span-4 md:mt-32':index===2?'md:col-span-5':'md:col-span-7 md:mt-20'}`}><div className={index===1?'aspect-[3/4] overflow-hidden':'aspect-[4/3] overflow-hidden'}><img src={project.coverImage} alt={project.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.02]"/></div><div className="project-caption"><span className="font-display text-2xl">0{index+1} — {project.title}</span><span>{project.category}</span></div></Link>)}</div></section>
<section className="grid bg-foreground text-background md:grid-cols-2"><div className="p-8 md:p-16"><span className="font-mono text-xs uppercase text-primary">Proyecto propio</span><h2 className="mt-5 font-display text-8xl uppercase md:text-9xl">Jhona</h2><p className="mt-6 max-w-md">Proyecto propio de fotografía y producción visual: dirección creativa, identidad, fotografía, edición, diseño y presencia digital.</p><Button asChild variant="editorialOutline" className="mt-8 border-background bg-foreground text-background"><Link to="/jhona-fotografia">Ver caso de estudio</Link></Button></div><div className="grid place-items-center bg-primary p-10"><img src={jhonaLogo} alt="Logo original de Jhona Diseño y Fotografía" className="h-auto w-full max-w-lg"/></div></section></main>}