import { Link } from "@tanstack/react-router";
import { Menu, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import logo from "@/assets/logojhona.webp.asset.json";

export const jhonaLogo = logo.url;
const workLinks = [["Branding", "/branding"], ["Diseño gráfico", "/diseno-grafico"], ["Fotografía", "/fotografia"], ["Retoque", "/retoque"]] as const;

export function SiteHeader() {
  const [open, setOpen] = useState(false);
  return <header className="sticky top-0 z-50 border-b border-foreground bg-background/95 backdrop-blur"><div className="grid h-16 grid-cols-[minmax(0,1fr)_auto] items-center px-5 md:px-10"><Link to="/" className="min-w-0 truncate font-display text-2xl uppercase">Isaac Espinoza</Link><nav className="hidden items-center gap-6 font-mono text-[10px] uppercase md:flex"><Link to="/">Inicio</Link><Link to="/proyectos">Proyectos</Link><Link to="/sobre-mi">Sobre mí</Link><div className="group relative py-5"><span>Trabajo</span><div className="invisible absolute right-0 top-full w-48 border border-foreground bg-background p-3 opacity-0 transition group-hover:visible group-hover:opacity-100">{workLinks.map(([label,to])=><Link key={to} to={to} className="block border-b border-border py-2 last:border-0">{label}</Link>)}</div></div><Link to="/jhona-fotografia">Jhona Fotografía</Link><Link to="/contacto">Contacto</Link></nav><button aria-label={open ? "Cerrar menú" : "Abrir menú"} className="grid size-10 place-items-center md:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open && <nav className="border-t border-foreground bg-background px-5 py-5 font-display text-3xl uppercase md:hidden">{[["Inicio","/"],["Proyectos","/proyectos"],["Sobre mí","/sobre-mi"],...workLinks,["Jhona Fotografía","/jhona-fotografia"],["Contacto","/contacto"]].map(([label,to])=><Link key={to} to={to} onClick={()=>setOpen(false)} className="block border-b border-border py-2">{label}</Link>)}</nav>}</header>
}
export function Placeholder({label, className="aspect-[4/3]"}:{label:string,className?:string}) { return <div className={`placeholder-frame ${className}`} role="img" aria-label={`Espacio reservado: ${label}`}><span>{label}<small>Imagen pendiente</small></span></div> }
export function PageIntro({number,title,children}:{number:string,title:string,children:ReactNode}) { return <section className="border-b border-foreground px-5 py-16 md:px-10 md:py-24"><span className="section-number">{number} /</span><h1 className="mt-5 max-w-6xl font-display text-6xl uppercase leading-[.9] md:text-9xl">{title}</h1><div className="mt-8 max-w-2xl text-lg leading-relaxed">{children}</div></section> }
export function SiteFooter() { return <footer className="border-t border-foreground bg-background px-5 py-12 md:px-10"><div className="grid gap-8 md:grid-cols-2"><h2 className="font-display text-5xl uppercase">¿Tenés un proyecto en mente?</h2><div className="font-mono text-xs uppercase leading-7 md:text-right"><a href="mailto:jhonadisenoyfotografia@gmail.com">jhonadisenoyfotografia@gmail.com</a><br/><a href="tel:+595982946365">+595 982 946365</a></div></div><div className="mt-16 flex justify-between border-t border-border pt-5 font-mono text-[9px] uppercase"><span>Isaac Espinoza</span><span>Diseño + Fotografía + Identidad</span></div></footer> }
export function WorkArchive({category}:{category:string}) { return <div className="grid grid-cols-1 gap-6 px-5 py-12 md:grid-cols-12 md:px-10"><article className="md:col-span-8"><Placeholder label={`${category} — proyecto 01`} className="aspect-[3/2]"/><h2 className="project-caption">Proyecto por incorporar <span>{category}</span></h2></article><article className="md:col-span-4"><Placeholder label={`${category} — proyecto 02`} className="aspect-[2/3]"/><h2 className="project-caption">Proyecto por incorporar <span>Case study</span></h2></article><article className="md:col-span-5"><Placeholder label={`${category} — proyecto 03`} className="aspect-square"/></article><article className="md:col-span-7"><Placeholder label={`${category} — proyecto 04`} className="aspect-[16/9]"/></article></div> }