/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CvRouteImport } from './routes/cv'
import { Route as DisenoGraficoRouteImport } from './routes/diseno-grafico'
import { Route as FotografiaRouteImport } from './routes/fotografia'
import { Route as JhonaFotografiaRouteImport } from './routes/jhona-fotografia'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as ProyectosSlugRouteImport } from './routes/proyectos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const DisenoGraficoRoute = DisenoGraficoRouteImport.update({
  id: '/diseno-grafico',
  path: '/diseno-grafico',
  getParentRoute: () => rootRouteImport,
} as any)
const FotografiaRoute = FotografiaRouteImport.update({
  id: '/fotografia',
  path: '/fotografia',
  getParentRoute: () => rootRouteImport,
} as any)
const JhonaFotografiaRoute = JhonaFotografiaRouteImport.update({
  id: '/jhona-fotografia',
  path: '/jhona-fotografia',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosSlugRoute = ProyectosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProyectosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/cv': typeof CvRoute
  '/diseno-grafico': typeof DisenoGraficoRoute
  '/fotografia': typeof FotografiaRoute
  '/jhona-fotografia': typeof JhonaFotografiaRoute
  '/proyectos': typeof ProyectosRouteWithChildren
  '/sobre-mi': typeof SobreMiRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/cv': typeof CvRoute
  '/diseno-grafico': typeof DisenoGraficoRoute
  '/fotografia': typeof FotografiaRoute
  '/jhona-fotografia': typeof JhonaFotografiaRoute
  '/proyectos': typeof ProyectosRouteWithChildren
  '/sobre-mi': typeof SobreMiRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/cv': typeof CvRoute
  '/diseno-grafico': typeof DisenoGraficoRoute
  '/fotografia': typeof FotografiaRoute
  '/jhona-fotografia': typeof JhonaFotografiaRoute
  '/proyectos': typeof ProyectosRouteWithChildren
  '/sobre-mi': typeof SobreMiRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/cv'
    | '/diseno-grafico'
    | '/fotografia'
    | '/jhona-fotografia'
    | '/proyectos'
    | '/sobre-mi'
    | '/proyectos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/cv'
    | '/diseno-grafico'
    | '/fotografia'
    | '/jhona-fotografia'
    | '/proyectos'
    | '/sobre-mi'
    | '/proyectos/$slug'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/cv'
    | '/diseno-grafico'
    | '/fotografia'
    | '/jhona-fotografia'
    | '/proyectos'
    | '/sobre-mi'
    | '/proyectos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  CvRoute: typeof CvRoute
  DisenoGraficoRoute: typeof DisenoGraficoRoute
  FotografiaRoute: typeof FotografiaRoute
  JhonaFotografiaRoute: typeof JhonaFotografiaRoute
  ProyectosRoute: typeof ProyectosRouteWithChildren
  SobreMiRoute: typeof SobreMiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseno-grafico': {
      id: '/diseno-grafico'
      path: '/diseno-grafico'
      fullPath: '/diseno-grafico'
      preLoaderRoute: typeof DisenoGraficoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografia': {
      id: '/fotografia'
      path: '/fotografia'
      fullPath: '/fotografia'
      preLoaderRoute: typeof FotografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jhona-fotografia': {
      id: '/jhona-fotografia'
      path: '/jhona-fotografia'
      fullPath: '/jhona-fotografia'
      preLoaderRoute: typeof JhonaFotografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/$slug': {
      id: '/proyectos/$slug'
      path: '/$slug'
      fullPath: '/proyectos/$slug'
      preLoaderRoute: typeof ProyectosSlugRouteImport
      parentRoute: typeof ProyectosRoute
    }
  }
}

interface ProyectosRouteChildren {
  ProyectosSlugRoute: typeof ProyectosSlugRoute
}

const ProyectosRouteChildren: ProyectosRouteChildren = {
  ProyectosSlugRoute: ProyectosSlugRoute,
}

const ProyectosRouteWithChildren = ProyectosRoute._addFileChildren(
  ProyectosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  CvRoute: CvRoute,
  DisenoGraficoRoute: DisenoGraficoRoute,
  FotografiaRoute: FotografiaRoute,
  JhonaFotografiaRoute: JhonaFotografiaRoute,
  ProyectosRoute: ProyectosRouteWithChildren,
  SobreMiRoute: SobreMiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
