/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as DisenoGraficoRouteImport } from './routes/diseno-grafico'
import { Route as FotografiaRouteImport } from './routes/fotografia'
import { Route as JhonaFotografiaRouteImport } from './routes/jhona-fotografia'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as RetoqueRouteImport } from './routes/retoque'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const DisenoGraficoRoute = DisenoGraficoRouteImport.update({
  id: '/diseno-grafico',
  path: '/diseno-grafico',
  getParentRoute: () => rootRouteImport,
} as any)
const FotografiaRoute = FotografiaRouteImport.update({
  id: '/fotografia',
  path: '/fotografia',
  getParentRoute: () => rootRouteImport,
} as any)
const JhonaFotografiaRoute = JhonaFotografiaRouteImport.update({
  id: '/jhona-fotografia',
  path: '/jhona-fotografia',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const RetoqueRoute = RetoqueRouteImport.update({
  id: '/retoque',
  path: '/retoque',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branding': typeof BrandingRoute
  '/contacto': typeof ContactoRoute
  '/diseno-grafico': typeof DisenoGraficoRoute
  '/fotografia': typeof FotografiaRoute
  '/jhona-fotografia': typeof JhonaFotografiaRoute
  '/proyectos': typeof ProyectosRoute
  '/retoque': typeof RetoqueRoute
  '/sobre-mi': typeof SobreMiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branding': typeof BrandingRoute
  '/contacto': typeof ContactoRoute
  '/diseno-grafico': typeof DisenoGraficoRoute
  '/fotografia': typeof FotografiaRoute
  '/jhona-fotografia': typeof JhonaFotografiaRoute
  '/proyectos': typeof ProyectosRoute
  '/retoque': typeof RetoqueRoute
  '/sobre-mi': typeof SobreMiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/branding': typeof BrandingRoute
  '/contacto': typeof ContactoRoute
  '/diseno-grafico': typeof DisenoGraficoRoute
  '/fotografia': typeof FotografiaRoute
  '/jhona-fotografia': typeof JhonaFotografiaRoute
  '/proyectos': typeof ProyectosRoute
  '/retoque': typeof RetoqueRoute
  '/sobre-mi': typeof SobreMiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branding'
    | '/contacto'
    | '/diseno-grafico'
    | '/fotografia'
    | '/jhona-fotografia'
    | '/proyectos'
    | '/retoque'
    | '/sobre-mi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branding'
    | '/contacto'
    | '/diseno-grafico'
    | '/fotografia'
    | '/jhona-fotografia'
    | '/proyectos'
    | '/retoque'
    | '/sobre-mi'
  id:
    | '__root__'
    | '/'
    | '/branding'
    | '/contacto'
    | '/diseno-grafico'
    | '/fotografia'
    | '/jhona-fotografia'
    | '/proyectos'
    | '/retoque'
    | '/sobre-mi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandingRoute: typeof BrandingRoute
  ContactoRoute: typeof ContactoRoute
  DisenoGraficoRoute: typeof DisenoGraficoRoute
  FotografiaRoute: typeof FotografiaRoute
  JhonaFotografiaRoute: typeof JhonaFotografiaRoute
  ProyectosRoute: typeof ProyectosRoute
  RetoqueRoute: typeof RetoqueRoute
  SobreMiRoute: typeof SobreMiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseno-grafico': {
      id: '/diseno-grafico'
      path: '/diseno-grafico'
      fullPath: '/diseno-grafico'
      preLoaderRoute: typeof DisenoGraficoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografia': {
      id: '/fotografia'
      path: '/fotografia'
      fullPath: '/fotografia'
      preLoaderRoute: typeof FotografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jhona-fotografia': {
      id: '/jhona-fotografia'
      path: '/jhona-fotografia'
      fullPath: '/jhona-fotografia'
      preLoaderRoute: typeof JhonaFotografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retoque': {
      id: '/retoque'
      path: '/retoque'
      fullPath: '/retoque'
      preLoaderRoute: typeof RetoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandingRoute: BrandingRoute,
  ContactoRoute: ContactoRoute,
  DisenoGraficoRoute: DisenoGraficoRoute,
  FotografiaRoute: FotografiaRoute,
  JhonaFotografiaRoute: JhonaFotografiaRoute,
  ProyectosRoute: ProyectosRoute,
  RetoqueRoute: RetoqueRoute,
  SobreMiRoute: SobreMiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
