/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as DisenoGraficoRouteImport } from './routes/diseno-grafico'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const DisenoGraficoRoute = DisenoGraficoRouteImport.update({
  id: '/diseno-grafico',
  path: '/diseno-grafico',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branding': typeof BrandingRoute
  '/diseno-grafico': typeof DisenoGraficoRoute
  '/proyectos': typeof ProyectosRoute
  '/sobre-mi': typeof SobreMiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branding': typeof BrandingRoute
  '/diseno-grafico': typeof DisenoGraficoRoute
  '/proyectos': typeof ProyectosRoute
  '/sobre-mi': typeof SobreMiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/branding': typeof BrandingRoute
  '/diseno-grafico': typeof DisenoGraficoRoute
  '/proyectos': typeof ProyectosRoute
  '/sobre-mi': typeof SobreMiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/branding' | '/diseno-grafico' | '/proyectos' | '/sobre-mi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/branding' | '/diseno-grafico' | '/proyectos' | '/sobre-mi'
  id:
    | '__root__'
    | '/'
    | '/branding'
    | '/diseno-grafico'
    | '/proyectos'
    | '/sobre-mi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandingRoute: typeof BrandingRoute
  DisenoGraficoRoute: typeof DisenoGraficoRoute
  ProyectosRoute: typeof ProyectosRoute
  SobreMiRoute: typeof SobreMiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseno-grafico': {
      id: '/diseno-grafico'
      path: '/diseno-grafico'
      fullPath: '/diseno-grafico'
      preLoaderRoute: typeof DisenoGraficoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandingRoute: BrandingRoute,
  DisenoGraficoRoute: DisenoGraficoRoute,
  ProyectosRoute: ProyectosRoute,
  SobreMiRoute: SobreMiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
